# Generated by Django 2.2.7 on 2019-11-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('businessID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('businessName', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('longitude', models.FloatField(blank=True, default=None)),
                ('latitude', models.FloatField(blank=True, default=None)),
                ('businessURL', models.CharField(blank=True, max_length=300)),
                ('pictureURL', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('reviewCount', models.IntegerField(blank=True, default=None)),
                ('zipcode', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YelpReviews',
            fields=[
                ('reviewID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, default=None)),
                ('date', models.DateField(db_index=True)),
                ('review', models.CharField(blank=True, max_length=5000)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse.Business')),
            ],
            options={
                'unique_together': {('reviewID', 'date')},
            },
        ),
    ]
