# Generated by Django 2.2.7 on 2019-12-03 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0003_business_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='success',
        ),
        migrations.CreateModel(
            name='BusinessAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.CharField(blank=True, max_length=100)),
                ('business', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse.Business')),
            ],
        ),
    ]
