# Generated by Django 2.2.6 on 2019-10-14 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0005_auto_20191014_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='YelpReviews',
            fields=[
                ('reviewID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, default=None)),
                ('date', models.DateField()),
                ('review', models.CharField(blank=True, max_length=5000)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.Business')),
            ],
            options={
                'unique_together': {('reviewID', 'date')},
            },
        ),
    ]
