# Generated by Django 2.2.6 on 2019-10-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0009_auto_20191016_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelpreviews',
            name='reviewID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
