# Generated by Django 2.2.6 on 2019-10-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0010_auto_20191016_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yelpreviews',
            name='business',
        ),
    ]
