# Generated by Django 2.2.6 on 2019-10-16 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0014_auto_20191016_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelpreviews',
            name='business',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse.Business'),
        ),
    ]
