# Generated by Django 2.2.6 on 2019-10-18 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0015_auto_20191016_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelpreviews',
            name='business',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse.Business'),
        ),
        migrations.AlterField(
            model_name='yelpreviews',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
