# Generated by Django 2.2.6 on 2019-10-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0002_auto_20191014_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='businessURL',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='business',
            name='pictureURL',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
