# Generated by Django 2.2.6 on 2019-10-14 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0003_auto_20191014_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='zipcode',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.Category'),
        ),
    ]
