# Generated by Django 2.2.6 on 2019-10-16 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0007_auto_20191015_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelpreviews',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse.Business'),
        ),
    ]
