# Generated by Django 2.2.6 on 2019-10-16 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0013_auto_20191016_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelpreviews',
            name='business',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse.Business'),
        ),
        migrations.AlterField(
            model_name='yelpreviews',
            name='reviewID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
