# Generated by Django 2.2.6 on 2019-10-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('businessID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('businessName', models.CharField(blank=True, max_length=100)),
                ('longitude', models.FloatField(blank=True, default=None)),
                ('latitude', models.FloatField(blank=True, default=None)),
                ('businessURL', models.CharField(blank=True, max_length=100)),
                ('pictureURL', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('reviewCount', models.IntegerField(blank=True, default=None)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
